version: '3.8'
services:
  nextwordpredictor-backend:
    container_name: "nextwordpredictor-backend"
    build:
      context: .
      dockerfile: DockerfileforBackend
    image: "nextwordpredictor-backend"
    ports:
      - "5060:5060"
    stdin_open: true
    restart: always
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    restart: always
    container_name: db_service
    command: --default-authentication-plugin=mysql_native_password
    # command: --init-file /data/application/init.sql
    environment:
      - "MYSQL_DATABASE=word_predictor_schema"
      - "MYSQL_USER=root_1"
      - "MYSQL_PASSWORD=root_1"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"
    volumes:
      - ./database_schema:/docker-entrypoint-initdb.d
      # - ./database_schema:/data/application
volumes:
  db:
    driver: local
