export default class ReducerConstants {
    static USER_CHANGED = "USER_CHANGED";
    static PREDICTIONS_RECEIVED = "PREDICTIONS_RECEIVED";
    static USER_TYPING_MESSAGE = "USER_TYPING_MESSAGE";
    static USER_SELECTED_PREDICTION = "USER_SELECTED_PREDICTION"
}
